//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Sem_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemView
    {
        public int Item_ID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> Sale { get; set; }
    }
}
