//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Sem_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderMst()
        {
            this.OrderDetailMsts = new HashSet<OrderDetailMst>();
        }
    
        public int ID { get; set; }
        public int User_ID { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [RegularExpression(@"^(([a-zA-Z])+([ ]{0,1})?)+$", ErrorMessage = "Can not have any special characters or numbers")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [RegularExpression(@"^(([a-zA-Z0-9])+([ ,-]*)?)+$", ErrorMessage = "Can not have any special characters or spaces")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [RegularExpression(@"^(([a-zA-Z])+([ ]{0,1})?)+$", ErrorMessage = "Can not have any special characters or numbers")]
        public string City { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [RegularExpression(@"^(([a-zA-Z])+([ ]{0,1})?)+$", ErrorMessage = "Can not have any special characters or numbers")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [Phone(ErrorMessage = "Please input valid phone number")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [EmailAddress(ErrorMessage = "Please input valid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Can not empty")]
        [CreditCard(ErrorMessage = "Please input valid credit card")]
        public string CreditCard { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailMst> OrderDetailMsts { get; set; }
        public virtual UserMst UserMst { get; set; }
    }
}
