//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Sem_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailMst
    {
        public int Order_ID { get; set; }
        public int Item_ID { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual ItemMst ItemMst { get; set; }
        public virtual OrderMst OrderMst { get; set; }
    }
}
